import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
death=pd.read_csv('coronadeaths.csv')
confirmed=pd.read_csv('coronaconfirmed.csv')
#Turkey
arr=np.array(confirmed.iloc[213:214,13:])
arr=arr.transpose()
arr=pd.DataFrame(arr)
arr=pd.DataFrame(arr.values.tolist(),columns=['Veriler'])
turkey=pd.DataFrame(arr)
günler=pd.DataFrame(np.arange(0,57),columns=['Günler'])
turkey=pd.concat([günler,turkey],axis=1)
plt.plot(turkey['Veriler'],color='red',marker='x')
plt.bar(turkey['Günler'],turkey['Veriler'])
plt.title("Türkiye'de İlk Vakadan Sonraki Günlük Korono Virüsü Vaka Sayısı")
plt.xlabel('Günler')
plt.ylabel('Vaka Sayısı')
ax=plt.subplot()
ax.set_xticks(np.arange(1,58,5))
günlükartıs = turkey['Veriler'].diff(1)
günlükartıs[0]=0
plt.show()
plt.title("Türkiye'de İlk Vakadan Sonraki Günlük Korono Virüsü Artış Sayısı")
plt.xlabel('Günler')
plt.ylabel('Vaka Sayısı')
ax=plt.subplot()
ax.set_xticks(np.arange(1,58,5))
plt.bar(turkey['Günler'],günlükartıs)
plt.show()
#Italy
arrıtaly=np.array(confirmed.iloc[137:138,13:])
arrıtaly=arrıtaly.transpose()
arrıtaly=pd.DataFrame(arrıtaly)
arrıtaly=pd.DataFrame(arrıtaly.values.tolist(),columns=['Veriler'])
ıtaly=pd.DataFrame(arrıtaly)
günlerıtaly=pd.DataFrame(np.arange(0,57),columns=['Günler'])
ıtaly=pd.concat([günlerıtaly,ıtaly],axis=1)
plt.plot(ıtaly['Veriler'],color='red',marker='x')
plt.bar(ıtaly['Günler'],ıtaly['Veriler'])
plt.title("İtalya'da İlk Vakadan Sonraki Günlük Korono Virüsü Vaka Sayısı")
plt.xlabel('Günler')
plt.ylabel('Vaka Sayısı')
ax=plt.subplot()
ax.set_xticks(np.arange(1,58,5))
günlükartısitaly = ıtaly['Veriler'].diff(1)
günlükartısitaly[0]=0
plt.show()
plt.title("İtalya'da İlk Vakadan Sonraki Günlük Korono Virüsü Artış Sayısı")
plt.xlabel('Günler')
plt.ylabel('Vaka Sayısı')
ax=plt.subplot()
ax.set_xticks(np.arange(1,58,5))
plt.bar(ıtaly['Günler'],günlükartısitaly)
plt.show()
#Spain
arrspain=np.array(confirmed.iloc[201:202,13:])
arrspain=arrspain.transpose()
arrspain=pd.DataFrame(arrspain)
arrspain=pd.DataFrame(arrspain.values.tolist(),columns=['Veriler'])
spain=pd.DataFrame(arrspain)
günlerspain=pd.DataFrame(np.arange(0,57),columns=['Günler'])
spain=pd.concat([günlerspain,spain],axis=1)
plt.plot(spain['Veriler'],color='red',marker='x')
plt.bar(spain['Günler'],spain['Veriler'])
plt.title("İspanya'da İlk Vakadan Sonraki Günlük Korono Virüsü Vaka Sayısı")
plt.xlabel('Günler')
plt.ylabel('Vaka Sayısı')
ax=plt.subplot()
ax.set_xticks(np.arange(0,56,5))
günlükartısspain = spain['Veriler'].diff(1)
günlükartısspain[0]=0
plt.show()
plt.title("İspanya'da İlk Vakadan Sonraki Günlük Korono Virüsü Artış Sayısı")
plt.xlabel('Günler')
plt.ylabel('Vaka Sayısı')
ax=plt.subplot()
ax.set_xticks(np.arange(0,56,5))
plt.bar(spain['Günler'],günlükartısspain)
plt.show()
plt.subplot(3,3,1)
plt.plot(turkey['Veriler'])
plt.subplot(3,3,2)
plt.plot(spain['Veriler'])
plt.subplot(3,3,3)
plt.plot(ıtaly['Veriler'])
plt.show()
#Karsılastırma
plt.plot(turkey['Veriler'])
plt.plot(spain['Veriler'])
plt.plot(ıtaly['Veriler'])
plt.legend(['Turkey','Spain','Italy'])
plt.show()
tr=turkey.iloc[40:,1:]
ıt=ıtaly.iloc[20:37,1:]
sp=spain.iloc[24:41,1:]
sp=pd.DataFrame(sp.values.tolist()) 
ıt=pd.DataFrame(ıt.values.tolist())
tr=pd.DataFrame(tr.values.tolist()) 
plt.plot(tr)
plt.plot(sp)
plt.plot(ıt)
plt.legend(['Spain','Turkey','Italy'])
plt.title('Aynı Gün Bazında Vaka Sayıları')
plt.show()
#Deaths
ıtdeaths=death.iloc[137:138,13:]
ıtdeaths=ıtdeaths.transpose()
ıtdeaths=pd.DataFrame(ıtdeaths.values.tolist(),columns=['Veriler'])
ıtdeaths=pd.concat([ıtdeaths,günler],axis=1)
plt.plot(ıtdeaths['Veriler'],color='red',marker='x')
plt.bar(ıtdeaths['Günler'],ıtdeaths['Veriler'])
plt.title("Italya'da Gün Bazlı Ölüm Sayısı")
plt.show()
trdeaths=death.iloc[213:214,13:]
trdeaths=trdeaths.transpose()
trdeaths=pd.DataFrame(trdeaths.values.tolist(),columns=['Veriler'])
trdeaths=pd.concat([trdeaths,günler],axis=1)
plt.plot(trdeaths['Veriler'],color='red',marker='x')
plt.bar(trdeaths['Günler'],trdeaths['Veriler'])
plt.title("Türkiye'de Gün Bazlı Ölüm Sayısı")
plt.show()
spdeaths=death.iloc[201:202,13:]
spdeaths=spdeaths.transpose()
spdeaths=pd.DataFrame(spdeaths.values.tolist(),columns=['Veriler'])
spdeaths=pd.concat([spdeaths,günler],axis=1)
plt.plot(spdeaths['Veriler'],color='red',marker='x')
plt.bar(spdeaths['Günler'],spdeaths['Veriler'])
plt.title("İspanya'da Gün Bazlı Ölüm Sayısı")
plt.show()
